language: node_js
node_js:
 - "lts/*"
cache:
 directories:
   - ~/.npm
   - ~/.cache


   
jobs:
 include:
   - stage: tests
     script:
     
       - docker run backstopjs/backstopjs -v tests/backstop:/src test
