language: node_js
node_js:
 - "lts/*"
cache:
 directories:
   - ~/.npm
   - ~/.cache


   
jobs:
 include:
   - stage: tests
     script:
       - docker build -t backstopjs/backstopjs
       - npm run backstop:ref 
       - npm run backstop:test
