language: node_js
node_js:
 - "lts/*"
cache:
 directories:
   - ~/.npm
   - ~/.cache


   
jobs:
 include:
   - stage: tests
     script:
  
       - docker pull backstopjs/backstopjs
       - docker run -d -p 127.0.0.1:80:3000 backstopjs/backstopjs  -c "src backstopjs/backstopjs; bundle exec reference; bundle exec test"
       
