language: node_js
node_js:
 - "lts/*"
cache:
 directories:
   - ~/.npm
   - ~/.cache


   
jobs:
 include:
   - stage: tests
     script:
        
        - docker run -p 127.0.0.1:80:3000 -v $(pwd)/tests:/src backstopjs/backstopjs test
        - docker ps -a
