language: node_js
node_js:
 - "lts/*"
cache:
 directories:
   - ~/.npm
   - ~/.cache


   
jobs:
 include:
   - stage: tests
     script:
       - docker build -t backstopjs/backstopjs
       - docker run -v ./tests/backstop:/src backstop:test
 
