language: node_js
node_js:
 - "lts/*"
cache:
 directories:
   - ~/.npm
   - ~/.cache


   
jobs:
 include:
   - stage: tests
     script:
     
       - docker run -d backstopjs/backstopjs  -c "src backstopjs/backstopjs;bundle exec test"
       
