language: node_js
node_js:
 - "lts/*"
cache:
 directories:
   - ~/.npm
   - ~/.cache
stages:
 - tests
 - name: master
   if: branch = master
 - name: tag
   if: tag IS present

jobs:
 include:
   - stage: tests
     before_install:
       npm start
     script:
       - docker build -t backstopjs/backstopjs
       - docker run -v ./tests/backstop:/src backstop:test
   - stage: tests
     script:
       - npm test
