language: node_js
node_js:
 - "lts/*"
cache:
 directories:
   - ~/.npm
   - ~/.cache


   
jobs:
 include:
   - stage: tests
     script:
        - docker ps -a
        - docker run backstopjs/backstopjs -f -v tests/backstop:/src test /bin/sh -c "cd /root/test; bundle exec npm run backstop:test;"
       
